### ISSUE TITLE
Pen not drawing from very begining

### ISSUE THREAD

**Issue by Ayan-Dhara** [untitled-team-101/Whiteboard#12]
When drawing with the pen it takes some time to start drawing.
So the path dragged in that time is not drawn.

The delay increase with screen size and if the page is zoomed out.

**Comment by Sundava** [comment]
Can I pick this one ? 

I took a quick look, and it seems to be related to the `save.saveUndoState();` in the `onMouseDownEvent` function.
Could this call be moved to the `onMouseUpEvent` instead ? Looks like the effect is the same after a quick testing

On a side not, it means that  `saveUndoState` could probably be optimized, at is seems to be a bit laggy

**Comment by tanmayVaish** [comment]
@Sundava I have assigned you, you can do what you can do and we can test it out, Good Luck!!

**Comment by Ayan-Dhara** [comment]
@Sundava  Yes you are absolutely right. Good Catch 👌.
moving `saveUndoState`   would most probably solve the issue.

If you want to optimize the `saveUndoState` function you can create another issue and PR. That will be great.

**Comment by Sundava** [comment]
After a bit more digging, moving `saveUndoState` breaks the undo/redo functionality, because the state is not saved at the right time.
I had to rework `undoRedo.js` in order to be able to save state at the end of the draw action instead of the beginning.
So it's only one PR, fixing this issue as a side effect
